version: '3.8'

services:
  nginx:
    build:
      context: ../../provisioning/local
      dockerfile: nginx.dockerfile
    ports:
      - 8001:80
    volumes:
      - ./:/var/www/html
      - ./storage/app/public:/var/www/html/public/storage
    depends_on:
      - php

  php:
    build:
      context: ../../provisioning/local
      dockerfile: php.dockerfile
    volumes:
      - ./:/var/www/html

  composer:
    build:
      context: ../../provisioning/local
      dockerfile: composer.dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html

  npm:
    image: node:current-alpine
    volumes:
      - ./:/var/www/html
    entrypoint: ["npm"]
    working_dir: /var/www/html

  artisan:
    build:
      context: ../../provisioning/local
      dockerfile: php.dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]

  please:
    build:
      context: ../../provisioning/local
      dockerfile: php.dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "/var/www/html/please"]

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1026}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8026}:8025'
